# Generated by Django 5.0.6 on 2024-07-10 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of the book', max_length=70)),
                ('publication_date', models.DateTimeField(help_text='Date the book was published', max_length=20)),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN number of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="the contributor's first name", max_length=50)),
                ('last_name', models.CharField(help_text='The contributors last name', max_length=50)),
                ('email', models.EmailField(help_text='the contact email for the contributor', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher', max_length=50)),
                ('website', models.URLField(help_text="The publisher's website")),
                ('email', models.EmailField(help_text="The publisher's email adress", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co_author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role the contributor had in this book')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributor',
            field=models.ManyToManyField(through='reviews.BookContributor', to='reviews.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The Review Text')),
                ('rating', models.IntegerField(help_text='the rating the reviewer has given')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='the date and time the review has been created')),
                ('date_edited', models.DateTimeField(help_text='The date and time the review was last edited', null=True)),
                ('book', models.ForeignKey(help_text='the book that this review is for', on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
